import type { ActorId, DialogueDefinition, DialogueLine, EpisodeDefinition, ProloguePage, QuestDefinition } from '../types';
import { pilotWorld } from './pilot-world';
import { pilotChallenges } from './pilot-challenges';
import { pilotMemories } from './pilot-memories';

const line = (speaker: ActorId | 'narrator', text: string): DialogueLine => ({ speaker, text });
const dialogue = (id: string, lines: DialogueLine[], optional?: DialogueDefinition['optional']): DialogueDefinition => ({ id, lines, optional });

const conversations: DialogueDefinition[] = [
  dialogue('bridge-thoughts', [
    line('narrator', 'Clark stops on Loeb Bridge. Below him, the river keeps moving.'),
    line('clark', 'Everyone else seems to know where they belong. Why does being near Lana make me feel like I am falling apart?'),
    line('narrator', 'An engine grows louder behind him. Tires scream against the road.'),
  ]),
  dialogue('morning', [
    line('jonathan', 'Morning, Clark. The fence can wait. That school bus will not.'),
    line('clark', 'I could make both. Finish the fence, catch the bus, try out for the team…'),
    line('jonathan', 'You could. But fitting in is not the same thing as hiding what matters about you.'),
    line('martha', 'Your dad means: be careful. I mean: remember to have a little fun.'),
    line('jonathan', 'Help me move that feed crate out of the path before you go. Gently, son.'),
  ], [{ label: 'Why do I have to be so careful?', lines: [line('clark', 'What if I could use what I can do to help people?'), line('jonathan', 'Then you should. Just remember that you are responsible for what happens afterward, too.')] }]),
  dialogue('friends', [
    line('pete', 'There he is. I was about to tell everyone you took the scenic route through Nebraska.'),
    line('clark', 'You would be surprised how quickly a person can get here.'),
    line('chloe', 'A mysterious arrival. An evasive answer. You are already giving the school newspaper something to work with.'),
    line('pete', 'Chloe has a theory about everything. Especially this town.'),
    line('chloe', 'A meteor shower hits, strange things keep happening, and everyone calls it coincidence. I prefer evidence.'),
    line('clark', 'Maybe some people just want an ordinary school day.'),
    line('pete', 'Then go say hello to Lana before the bell. That is ordinary. Mostly.'),
  ], [{ label: 'Ask about the Wall of Weird', lines: [line('chloe', 'Clippings, photographs, eyewitness reports. All the things Smallville would rather forget, in one place.'), line('clark', 'Sounds like a lot of secrets for one wall.'), line('chloe', 'Good thing I am not running out of pins.')] }]),
  dialogue('lana-school', [
    line('lana', 'Clark? You look a little pale. Are you all right?'),
    line('clark', 'Just the run to school. I missed the bus again.'),
    line('narrator', 'A green stone hangs from Lana’s necklace. As she steps closer, the strength drains from Clark’s legs.'),
    line('lana', 'This was made from a stone from the meteor shower. A reminder of my parents.'),
    line('clark', 'I am sorry, Lana. I did not know.'),
    line('narrator', 'He wants to stay. Instead, he takes a step back—and can breathe again.'),
  ]),
  dialogue('lex-rescue', [
    line('lex', 'The car went through the railing. I saw you on the bridge. How are you standing here?'),
    line('clark', 'You hit the water. I got you out. That is what matters.'),
    line('lex', 'I have spent my life around people who want something from me. You jumped into a river.'),
    line('clark', 'You needed help.'),
    line('lex', 'Lex Luthor. And I think I owe you more than a thank-you.'),
    line('clark', 'Clark Kent. You do not owe me anything.'),
  ], [{ label: 'Ask why Lex is in Smallville', lines: [line('lex', 'My father put me in charge of the local plant. His idea of a fresh start looks a lot like exile.'), line('clark', 'Smallville might surprise you.'), line('lex', 'It already has.')] }]),
  dialogue('truth', [
    line('jonathan', 'We heard about the bridge. You did the right thing, Clark.'),
    line('clark', 'A car hit me, Dad. I should be in a hospital. I need an answer that is not “be careful.”'),
    line('martha', 'We knew this conversation would come. We just wanted you to have a childhood first.'),
    line('jonathan', 'The day the meteors fell, your mother and I found you. There was no one else with you.'),
    line('clark', 'You told me I was adopted. What are you not telling me?'),
    line('jonathan', 'Come to the storm cellar by the barn. There is something we have kept safe for you all these years.'),
  ]),
  dialogue('ship', [
    line('narrator', 'Under an old canvas sheet is a small, unfamiliar craft. Its surface catches the light like nothing built on Earth.'),
    line('jonathan', 'This brought you to us. We do not know where it came from.'),
    line('clark', 'So I am not just different. I am from somewhere else.'),
    line('martha', 'You are our son. Finding out where your story began does not change where you belong.'),
    line('clark', 'I need some air. Somewhere quiet.'),
  ], [{ label: 'Look at the symbols', lines: [line('narrator', 'Strange markings line the edge of the craft. Clark traces them, but they offer no answers yet.'), line('jonathan', 'When you are ready to look for answers, you will not have to look alone.')] }]),
  dialogue('cemetery', [
    line('lana', 'I come here when I need to talk. It probably sounds strange.'),
    line('clark', 'Tonight, strange feels familiar.'),
    line('lana', 'People tell me what my parents were like. Sometimes I wish I had just one more memory of my own.'),
    line('clark', 'I found out something about my family. Now I do not know where I fit.'),
    line('lana', 'Maybe fitting somewhere is not something you find all at once.'),
    line('narrator', 'For a little while, the quiet is shared. Then Clark finds the question he has been carrying around all day.'),
    line('clark', 'The spring formal is tonight. I keep thinking I should have asked you to go with me.'),
    line('lana', 'Clark… I am going with Whitney. I said yes to him last week.'),
    line('clark', 'Right. Of course you are. Forget I said anything.'),
    line('lana', 'Do not do that. Come anyway—and if you do, I promise I will save you the last dance.'),
    line('narrator', 'She says it like it is already settled. Clark walks home with it turning over in his head.'),
  ], [{ label: 'Ask about the necklace', lines: [line('lana', 'I gave it to Whitney for the game. He says it is good luck.'), line('narrator', 'Without the green stone between them, Clark notices how easy it is to stand beside her.')] }]),
  dialogue('mansion', [
    line('lex', 'Clark. I thought a truck might be a better thank-you than a card.'),
    line('clark', 'My dad says we cannot accept it. Helping somebody is not something we charge for.'),
    line('lex', 'Your father has a very clear picture of the Luthor name.'),
    line('clark', 'I am trying to get to know the person who has it.'),
    line('lex', 'Then let us start there. Two people who did not exactly choose the lives they inherited.'),
    line('narrator', 'A friendship takes its first uncertain step. Back at school, Chloe has found something she wants Clark to see.'),
  ], [{ label: 'Ask about Lex’s father', lines: [line('lex', 'My father measures people by what they win. I am still working out what I want to measure.'), line('clark', 'You could start with what you do next.'), line('lex', 'That sounds almost dangerously hopeful.')] }]),
  dialogue('wall', [
    line('chloe', 'Three former football players attacked. The same young man near every scene. And this photograph from 1989.'),
    line('pete', 'He looks exactly the same. That is twelve years, Clark.'),
    line('clark', 'Who is he?'),
    line('chloe', 'Jeremy Creek. I pulled a yearbook, a hospital report, and coverage of the meteor shower. Have a look.'),
    line('narrator', 'Three pieces of a story. The next answer is on the wall, not in a rumor.'),
  ]),
  dialogue('yearbook', [
    line('narrator', 'A faded yearbook shows Jeremy Creek with the freshman class of 1989. A handwritten note points to an ugly homecoming tradition.'),
    line('pete', 'The team picked a kid and left him tied in a field. They called him the scarecrow.'),
    line('clark', 'That is not a tradition. That is somebody getting hurt.'),
  ]),
  dialogue('hospital', [
    line('narrator', 'A hospital report connects Jeremy’s disappearance to a power failure during an electrical storm. His long coma ended that night.'),
    line('chloe', 'Now the people who hurt him are being attacked. And the electrical damage at each scene is the same.'),
    line('clark', 'He has not come home to start over. He has come back to settle something.'),
  ]),
  dialogue('meteor-article', [
    line('narrator', 'A photograph shows a little girl after the meteor shower. It is Lana. The same day Clark arrived, her parents died.'),
    line('clark', 'All these things happened on the same day.'),
    line('chloe', 'Clark? This is not your fault. You were a child.'),
    line('narrator', 'He understands the words. Believing them will take longer.'),
  ]),
  dialogue('deduction', [
    line('clark', 'Jeremy has not aged since the meteors. The storm woke him up, and now he can use electricity.'),
    line('chloe', 'So we have a name, a pattern, and a reason. We still do not know where he will go next.'),
    line('pete', 'The homecoming dance is tonight. Most of the school will be there.'),
    line('clark', 'Keep looking. I need a minute outside.'),
  ]),
  dialogue('whitney', [
    line('whitney', 'Kent. The team has a homecoming tradition, and this year you are part of it.'),
    line('clark', 'Whitney, this is not funny.'),
    line('narrator', 'Lana’s green necklace glints in Whitney’s hand. Clark’s knees buckle before he can step away.'),
    line('narrator', 'The road gives way to rows of corn. When the truck leaves, Clark is alone in Riley Field.'),
  ]),
  dialogue('jeremy-field', [
    line('jeremy', 'Twelve years. And they are still doing it.'),
    line('clark', 'Jeremy? Help me down. You know what this feels like.'),
    line('jeremy', 'I thought punishing the people who did it to me would change something. I was wrong.'),
    line('clark', 'Whatever happened to you, the people at that dance did not all do it.'),
    line('jeremy', 'You are safer here.'),
    line('narrator', 'Jeremy walks toward the road. Clark strains against the ropes, but the green stone keeps him weak.'),
  ]),
  dialogue('lex-field', [
    line('clark', 'Help! Over here!'),
    line('lex', 'Clark? Who did this to you? Hold still.'),
    line('narrator', 'Lex loosens the ropes. The necklace falls into the dirt, and Clark’s strength returns.'),
    line('clark', 'There is someone headed for the school. I have to stop him.'),
    line('lex', 'Clark, wait—'),
    line('narrator', 'The boy who pulled Lex from the river is already disappearing down the path.'),
  ]),
  dialogue('jeremy-school', [
    line('clark', 'Jeremy. Step away from the sprinklers.'),
    line('jeremy', 'You got out. You should understand why I am doing this.'),
    line('clark', 'I understand being hurt. It does not give either of us the right to hurt everyone else.'),
    line('narrator', 'Electricity snaps across the service yard. Behind the gym doors, the dance goes on.'),
    line('clark', 'Whatever happens next, it ends out here.'),
  ]),
  dialogue('jeremy-saved', [
    line('narrator', 'Water pours out of the damaged truck. The electrical glow is gone. Clark pulls the door free and helps Jeremy out.'),
    line('jeremy', 'Where am I? What happened?'),
    line('clark', 'You are in Smallville. You are safe now.'),
    line('jeremy', 'I just want to go home.'),
    line('narrator', 'Clark stays until help arrives. For tonight, saving someone means staying beside them.'),
  ]),
  dialogue('home', [
    line('jonathan', 'Your mother told me you were back. Rough night?'),
    line('clark', 'I missed the dance. I found out more about myself than I wanted to. And I still have homework.'),
    line('jonathan', 'You also brought people home who might not have made it without you.'),
    line('clark', 'What if what I am puts the people I care about in danger?'),
    line('jonathan', 'What you are is still a question. Who you choose to be is something you can answer every day.'),
    line('martha', 'And whoever that turns out to be, there is always a light on for you here.'),
  ], [{ label: 'Ask about the future', lines: [line('clark', 'Do you think there is a reason I ended up here?'), line('jonathan', 'I think we found you. And I think, for tonight, that can be enough.')] }]),
  dialogue('loft', [
    line('narrator', 'Up in the loft, the telescope points beyond the fields. Somewhere across town, the dance is ending.'),
    line('clark', 'Maybe one day I will know how to tell her everything.'),
    line('narrator', 'A sound on the boards below. Lana is standing in the barn in the dress from the formal, one hand held out.'),
    line('lana', 'You came after all. I told you I was saving you the last dance.'),
    line('narrator', 'There is no music down there, and it does not matter. They turn slowly in the lamplight, and for once nothing about Clark is strange.'),
    line('clark', 'I could stay right here.'),
    line('narrator', 'Then the wind moves through the corn, and the barn below him is empty. It was only ever a daydream.'),
    line('narrator', 'Clark leans back into the telescope. Far down the road Lana is walking home—and she stops, and looks back toward the farm.'),
    line('clark', 'Goodnight, Lana.'),
    line('narrator', 'He lifts his eyes past the weathervane, past the fields, to the stars he fell from.'),
    line('narrator', 'The world is a little less ordinary than it was this morning. The boy looking up at it is still Clark Kent—for now. Every legend starts somewhere. This one starts here.'),
  ]),
];

const quests: QuestDefinition[] = [
  { id: 'morning', chapter: 0, title: 'A place to call home', description: 'Find Jonathan outside the barn. Even extraordinary days begin with chores.', location: 'farm', point: [0, 1.7], checkpoint: [0, 3.4], action: 'Talk to Jonathan', kind: 'talk', actor: 'jonathan', dialogue: 'morning' },
  { id: 'feed-crate', completionToast: { title:'A gentle touch', text:'Crate moved. The first bell is waiting.' }, chapter: 0, title: 'A gentle touch', description: 'Move the feed crate with your strength. Some things are easier when you remember to be careful.', location: 'farm', point: [1.7, 1.6], action: 'Move the feed crate', kind: 'strength', holdSeconds: 1.5 },
  { id: 'friends', chapter: 0, title: 'The first bell', description: 'You missed the bus. Beat it to school through the fields. Hold Shift or SPEED, then meet Pete and Chloe.', location: 'school', point: [-1.5, 1.5], checkpointLocation:'farm', checkpoint:[0,3.4], action: 'Meet your friends', kind: 'race', timeLimit:60, timerLabel:'BEAT THE SCHOOL BUS', actor: 'pete', dialogue: 'friends' },
  { id: 'lana', chapter: 0, title: 'A little green stone', description: 'Say hello to Lana near the school steps.', location: 'school', point: [1.8, 1.3], action: 'Talk to Lana', kind: 'talk', actor: 'lana', dialogue: 'lana-school', radius: 2.1 },
  { id: 'bridge-moment', chapter: 1, title: 'A moment above the river', description: 'Walk onto Loeb Bridge and take a moment to think.', location: 'bridge', point: [0, 0], checkpoint: [-3.4, 1.6], action: 'Look out over the river', kind: 'talk', dialogue: 'bridge-thoughts', radius: 1.2 },
  { id: 'car-door', completionToast: { title:'You have him', text:'Bring Lex to the marked riverbank.' }, chapter: 1, title: 'A second changes everything', description: 'The car struck you and plunged into the river. Reach it and free the driver.', location: 'bridge', point: [0, -1.7], checkpoint: [-3.4, 1.6], action: 'Dive & open the car', kind: 'rescue', holdSeconds: 1.7, radius: 1.15, arrivalText: 'Someone is trapped inside. Get into the water.' },
  { id: 'bring-lex-ashore', chapter: 1, title: 'Back to the surface', description: 'You have Lex. Carry him to the marked riverbank.', location: 'bridge', point: [3, 1.5], checkpoint: [0, -1.5], action: 'Help Lex onto the bank', kind: 'rescue', holdSeconds: 1.3, radius: 1.3 },
  { id: 'lex-thanks', chapter: 1, title: 'An unlikely beginning', description: 'Make sure Lex is all right.', location: 'bridge', point: [3, 1.5], action: 'Talk to Lex', kind: 'talk', actor: 'lex', dialogue: 'lex-rescue' },
  { id: 'family-truth', chapter: 2, title: 'The answers at home', description: 'Return to Jonathan. You need to understand how you survived the bridge.', location: 'farm', point: [0, 1.7], action: 'Ask Jonathan for the truth', kind: 'talk', actor: 'jonathan', dialogue: 'truth' },
  { id: 'spaceship', chapter: 2, title: 'Somewhere beyond the stars', description: 'Examine the craft hidden in the storm cellar beside the barn.', location: 'farm', point: [-2, 0.5], checkpoint: [0, 2.8], action: 'Uncover the spacecraft', kind: 'inspect', dialogue: 'ship' },
  { id: 'cemetery', chapter: 2, title: 'A quiet kind of understanding', description: 'Take a walk to the cemetery. Lana is there, remembering her parents.', location: 'cemetery', point: [0.4, 1.5], action: 'Sit with Lana', kind: 'talk', actor: 'lana', dialogue: 'cemetery' },
  { id: 'mansion', chapter: 2, title: 'More than a name', description: 'Visit Lex at the mansion and talk about his gift.', location: 'mansion', point: [0, 1.7], action: 'Talk to Lex', kind: 'talk', actor: 'lex', dialogue: 'mansion' },
  { id: 'wall', chapter: 3, title: 'Welcome to the Wall of Weird', description: 'Chloe has news about the attacks. Find her by the newspaper board at school.', location: 'school', point: [4.2, 0.6], action: 'Hear Chloe’s theory', kind: 'talk', actor: 'chloe', dialogue: 'wall' },
  { id: 'yearbook', chapter: 3, title: 'The boy in the photograph', description: 'Inspect the yearbook pinned to the left side of the board.', location: 'school', point: [3.5, -0.1], action: 'Examine the 1989 yearbook', kind: 'inspect', dialogue: 'yearbook', radius: 1.6 },
  { id: 'hospital', chapter: 3, title: 'Twelve missing years', description: 'Read the hospital report on the newspaper table.', location: 'school', point: [4.8, 0.6], action: 'Read the hospital report', kind: 'inspect', dialogue: 'hospital' },
  { id: 'meteor-article', chapter: 3, title: 'The day the sky fell', description: 'Look at the meteor-shower clipping. A familiar face is in the photograph.', location: 'school', point: [4.6, -0.1], action: 'Read the meteor clipping', kind: 'inspect', dialogue: 'meteor-article' },
  { id: 'deduction', chapter: 3, title: 'Connect the pieces', description: 'Share what you have found with Chloe and Pete.', location: 'school', point: [4.2, 0.6], action: 'Connect the clues', kind: 'talk', actor: 'chloe', dialogue: 'deduction' },
  { id: 'whitney', chapter: 4, title: 'An old tradition', description: 'Step outside to the school parking area. Whitney is waiting.', location: 'school', point: [2.9, 3.1], action: 'Face Whitney', kind: 'talk', actor: 'whitney', dialogue: 'whitney' },
  { id: 'jeremy-field', enterAt: { location:'cornfield', point:[0,.5] }, chapter: 4, title: 'History repeats', description: 'The necklace has taken your strength. Talk to Jeremy from the scarecrow post.', location: 'cornfield', point: [0, 0.8], checkpoint: [0, 0.5], action: 'Talk to Jeremy', kind: 'talk', actor: 'jeremy', dialogue: 'jeremy-field', radius: 2.5 },
  { id: 'call-for-help', chapter: 4, title: 'A friend in the dark', description: 'A car is passing the field. Call out to Lex.', location: 'cornfield', point: [0, 0.8], checkpoint: [0, 0.5], action: 'Call for help', kind: 'talk', actor: 'lex', dialogue: 'lex-field', radius: 2.5 },
  { id: 'race', enterAt: { location:'cornfield', point:[0,2.4] }, chapter: 5, title: 'Before the music stops', description: 'Reach Jeremy outside the school gym. Use your speed—the dance is about to begin.', location: 'school', point: [-3.9, 0.5], checkpointLocation: 'cornfield', checkpoint: [0, 2.4], action: 'Stop Jeremy', kind: 'race', timeLimit: 55, actor: 'jeremy', dialogue: 'jeremy-school', radius: 2.3 },
  { id: 'sprinklers', chapter: 5, title: 'Keep them safe', description: 'Force the sprinkler valve shut before Jeremy reaches it.', location: 'school', point: [-3.9, -1], checkpoint: [-3.7, 2.8], action: 'Seal the sprinkler valve', kind: 'strength', holdSeconds: 1.8, radius: 1.5 },
  { id: 'truck', completionToast: { title:'The water line breaks', text:'The electrical glow fades. Get Jeremy out.' }, chapter: 5, title: 'Stand your ground', description: 'Face Jeremy’s truck. Press E or tap Stop before it reaches you.', location: 'school', point: [-4.5, 1.7], checkpoint: [-3.7, 2.8], action: 'Hold back the truck', kind: 'strength', holdSeconds: 2.3, radius: 1.65 },
  { id: 'free-jeremy', chapter: 5, title: 'Everybody gets to go home', description: 'The truck hit a water line. Pull open the door and help Jeremy out.', location: 'school', point: [-4.5, 1.7], checkpoint: [-3.7, 2.8], action: 'Free Jeremy', kind: 'rescue', holdSeconds: 1.6, dialogue: 'jeremy-saved', radius: 1.65 },
  { id: 'home', chapter: 6, title: 'The light in the window', description: 'The school is safe. Head home and find your family by the barn.', location: 'farm', point: [0, 1.7], action: 'Talk with your family', kind: 'talk', actor: 'jonathan', dialogue: 'home' },
  { id: 'loft', chapter: 7, title: 'Every legend starts somewhere', description: 'Take one last look at the stars from the barn loft.', location: 'farm', point: [-2, 0.5], checkpoint: [0, 2.8], action: 'Look toward tomorrow', kind: 'inspect', dialogue: 'loft' },
];

export const prologue:ProloguePage[] = [
  { effect: 'meteors', year: 'OCTOBER 1989', title: 'The day the sky fell.', text: 'A quiet Kansas morning. Then the sky breaks open. Meteors rain over Smallville, leaving behind loss, unanswered questions—and a child.' },
  { year: 'A ROAD OUTSIDE SMALLVILLE', title: 'Something worth finding.', text: 'Jonathan and Martha Kent find a little boy beside an impossible craft. They do not know where he came from. They know they will not leave him behind.' },
  { year: 'TWELVE YEARS LATER', title: 'A boy. A town. A secret.', text: 'They name him Clark. He grows up among red barns and endless fields, learning that some things about him are extraordinary. This is where you step into his story.' },
];

export const pilot: EpisodeDefinition = {
  id: 's01e01', season: 1, number: 1, year: 2001, title: 'Pilot',
  description: 'A boy with extraordinary abilities. A town with extraordinary secrets. One day that changes everything.',
  chapters: [
    { title: 'An ordinary morning', caption: 'A home. A school. A secret.' },
    { title: 'The bridge', caption: 'Two lives, changed in a second.' },
    { title: 'Where we belong', caption: 'Some answers lead to more questions.' },
    { title: 'The Wall of Weird', caption: 'The past is not finished with Smallville.' },
    { title: 'The scarecrow', caption: 'Being different should not mean being alone.' },
    { title: 'A choice to help', caption: 'Strength is what you do with it.' },
    { title: 'Coming home', caption: 'There is always a light on.' },
    { title: 'A beginning', caption: 'The rest of the story is still unwritten.' },
  ],
  quests:quests.map(quest=>({...quest,challenge:pilotChallenges[quest.id]})),
  world: pilotWorld,
  memories:pilotMemories,
  prologue,
  tagline: 'Some secrets are bigger than a small town.',
  openingHint: { title:'Smallville, Kansas · 2001', text:'Your story begins at home. Find Jonathan near the barn.' },
  ending: { title: 'This is only', emphasis: 'the beginning.', summary: 'You saved two lives, found a few answers, and made it home. That sounds like Clark Kent.' },
  dialogues: Object.fromEntries(conversations.map(conversation => [conversation.id, conversation])),
  nextEpisode: { title: 'Metamorphosis', number: 2, available: false },
};
